{
  pkgs,
  osConfig,
  ...
}: let
  sensitivity =
    if osConfig.networking.hostName == "fw12"
    then "-0.2"
    else "-0.6";
in {
  # Additional hyde speific config
  imports = [
    ./hyprland.nix
  ];

  # hydenix home-manager options go here
  hydenix.hm = {
    enable = true; # enable home-manager module
    comma.enable = true; # useful nix tool to run software without installing it first
    dolphin.enable = false; # file manager
    editors.enable = false;
    fastfetch.enable = true; # fastfetch configuration
    firefox.enable = true; # enable firefox module
    git.enable = false;
    hyde.enable = true; # enable hyde module
    hyprland = {
      enable = true; # enable hyprland module
      extraConfig = ''
        input {
          touchpad {
            natural_scroll = true
            scroll_factor = 0.5
          }
          sensitivity = ${sensitivity}
        }
      '';
      # Animation configurations
      animations = {
        enable = true; # enable animation configurations
        preset = "LimeFrenzy"; # string from override or default: "standard" # or "LimeFrenzy", "classic", "diablo-1", "diablo-2", "disable", "dynamic", "end4", "fast", "high", "ja", "me-1", "me-2", "minimal-1", "minimal-2", "moving", "optimized", "standard", "vertical"
        extraConfig = ""; # additional animation configuration
        overrides = {}; # override specific animation files by name
      };
      # Shader configurations
      shaders = {
        enable = false; # enable shader configurations
      };
      # Workflow configurations
      workflows = {
        enable = true; # enable workflow configurations
        active = "default"; # string from override or default: "default" # or "editing", "gaming", "powersaver", "snappy"
        overrides = {}; # override or add custom workflows
      };
      # Hypridle configurations
      hypridle = {
        enable = true; # enable hypridle configurations
        extraConfig = ""; # additional hypridle configuration
        overrideConfig = null; # complete hypridle configuration override (null or lib.types.lines)
      };
      # Keybindings configurations
      keybindings = {
        enable = true; # enable keybindings configurations
        overrideConfig = null; # complete keybindings configuration override (null or lib.types.lines)
      };
      # Window rules configurations
      windowrules = {
        enable = true; # enable window rules configurations
        extraConfig = ''
          windowrule {
            name = windowrule-1
            float = on
            size = (monitor_w*0.5) (monitor_h*0.5)
            center = on
            match:title = ^(omnia)$
          }
        ''; # additional window rules configuration
        overrideConfig = null; # complete window rules configuration override (null or lib.types.lines)
      };
      # NVIDIA configurations
      nvidia = {
        enable = false; # enable NVIDIA configurations (defaults to config.hardware.nvidia.enabled)
        extraConfig = ""; # additional NVIDIA configuration
        overrideConfig = null; # complete NVIDIA configuration override (null or lib.types.lines)
      };
      # Pyprland configurations
      pyprland = {
        enable = true; # enable pyprland configurations
        extraConfig = ""; # additional pyprland configuration
        overrideConfig = null; # complete pyprland configuration override (null or lib.types.lines)
      };

      # Monitor configurations
      monitors = {
        enable = true; # enable monitor configurations
        overrideConfig = ''
          # Generated by nwg-displays on 2025-03-11 at 12:34:34. Do not edit manually.

          monitor=DP-1,1920x1080@144.0,840x0,1.0
          monitor=DP-1,transform,3
          monitor=HDMI-A-1,1920x1080@144.0,1920x0,1.0
          monitor=eDP-1,1920x1080@144.0,3840x0,1.25
          monitor=eDP-2,2560x1600@120.0,1536x928,2.0
          monitor=DP-2,1920x1080@120.0,0x1080,1.0
          monitor=DP-3,1920x1080@120.0,0x0,1.0
          monitor=DP-12,1920x1080@120.0,0x1080,1.00
          monitor=DP-13,1920x1080@120.0,0x0,1.00
          monitor=DP-10,2560x1600@60.0,0x1203,1.33
          monitor=DP-11,2560x1600@60.0,0x0,1.33
        ''; # complete monitor configuration override (null or lib.types.lines)
      };
    };
    lockscreen = {
      enable = true; # enable lockscreen module
      hyprlock = true; # enable hyprlock lockscreen
      swaylock = false; # enable swaylock lockscreen
    };
    notifications.enable = true; # enable notifications module
    qt.enable = true; # enable qt module
    rofi.enable = true; # enable rofi module
    screenshots = {
      enable = true; # enable screenshots module
      grim.enable = true; # enable grim screenshot tool
      slurp.enable = true; # enable slurp region selection tool
      satty.enable = false; # enable satty screenshot annotation tool
      swappy.enable = true; # enable swappy screenshot editor
    };
    shell = {
      enable = true; # enable shell module
      zsh.enable = false;
      bash.enable = false; # enable bash shell
      fish.enable = false; # enable fish shell
      pokego.enable = true; # enable Pokemon ASCII art scripts
      p10k.enable = false; # enable p10k prompt
      starship.enable = false; # enable starship prompt
    };
    social = {
      enable = true; # enable social module
      discord.enable = true; # enable discord module
      vesktop.enable = true; # enable vesktop module
    };
    spotify.enable = true; # enable spotify module
    swww.enable = true; # enable swww wallpaper daemon
    terminals = {
      enable = true; # enable terminals module
      kitty = {
        enable = true; # enable kitty terminal
        configText = ""; # kitty config text
      };
    };
    theme = {
      enable = true; # enable theme module
      active = "Catppuccin Mocha"; # active theme name
      themes = ["Catppuccin Mocha" "Catppuccin Latte" "BlueSky" "Green Lush"]; # default enabled themes, full list in https://github.com/richen604/hydenix/tree/main/hydenix/sources/themes
    };
    waybar = {
      enable = true; # enable waybar module
      userStyle = ""; # custom waybar user-style.css
    };
    wlogout.enable = true; # enable wlogout module
    xdg.enable = false; # enable xdg module
  };
}
