return { "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  opts = {
      ensure_installed = {
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cuda",
        "diff",
        "gitcommit",
        "gitignore",
        "go",
        "html",
        "java",
        "javascript",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "nix",
        "ocaml",
        "query",
        "tmux",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
        "zig" },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
  }
}
